version: "3.7"
services:
  app:
    build: .
    container_name: cocuschallenge
    environment:
       GITHUB_TOKEN: "${GITHUB_TOKEN}"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules